#cloud-config
users:
- name: fatesaikou
  groups: sudo
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  ssh_authorized_keys: ${FATESAIKOU_KEYS}
- name: sshproxy
  shell: /bin/bash
  ssh_authorized_keys: ${SSHPROXY_KEYS}

package_update: true
package_upgrade: true

packages:
- vim
- tmux
- git
- rclone
- python3
- nodejs

write_files:
- content: |
    ${FATESAIKOU_BASHRC}
  path: /.bashrc
- content: |
    ${FATESAIKOU_TMUXCONF}
  path: /.tmux.conf