#cloud-config
users:
- name: fatesaikou
  # groups: sudo
  # sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  ssh_authorized_keys: ${FATESAIKOU_KEYS}
- name: sshproxy
  shell: /bin/bash
  ssh_authorized_keys: ${SSHPROXY_KEYS}

package_update: true
package_upgrade: true

packages:
- vim
- tmux
- git
- rclone
- python3
- nodejs

write_files:
- content: ${FATESAIKOU_BASHRC_BASE64}
  path: /home/fatesaikou/.bashrc_base64
- content: ${FATESAIKOU_TMUXCONF_BASE64}
  path: /home/fatesaikou/.tmux.conf_base64

runcmd:
- cat /home/fatesaikou/.bashrc_base64 | base64 -d > /home/fatesaikou/.bashrc
- cat /home/fatesaikou/.tmux.conf_base64 | base64 -d > /home/fatesaikou/.tmux.conf