#cloud-config
users:
- name: fatesaikou
  groups: sudo
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  ssh_authorized_keys: ${FATESAIKOU_KEYS}
- name: sshproxy
  shell: /bin/bash
  ssh_authorized_keys: ${SSHPROXY_KEYS}

package_update: true
package_upgrade: true

packages:
- vim
- tmux
- git
- rclone
- python3
- nodejs

runcmd: [
  # Disable root login"
  "sed -i '/PermitRootLogin/d' /etc/ssh/sshd_config",
  "echo \"PermitRootLogin no\" >> /etc/ssh/sshd_config",
  "systemctl restart sshd",
  # Copy synced files
  ${SYNC_FILE_CMDS}
  "chown -R fatesaikou:fatesaikou /home/fatesaikou/"
]