name: Create linode

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        description: instance label
        required: true
        default: fws
      region:
        type: string
        description: instance region
        required: true
        default: ap-northeast
      type:
        type: string
        description: instance type
        required: true
        default: g6-nanode-1
      image:
        type: string
        description: instance image
        required: true
        default: linode/ubuntu24.04
  workflow_call:
    inputs:
      label:
        type: string
        description: instance label
        required: true
        default: fws
      region:
        type: string
        description: instance region
        required: true
        default: ap-northeast
      type:
        type: string
        description: instance type
        required: true
        default: g6-nanode-1
      image:
        type: string
        description: instance image
        required: true
        default: linode/ubuntu24.04
      
jobs:
  create_linode:
    name: create linode
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Install the Linode CLI
      uses: linode/action-linode-cli@v1
      with:
        token: ${{ secrets.LINODE_TOKEN }}

    - name: Install nessary tools
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Generate tmp password
      run: |
        ROOT_PASS=$(openssl rand -base64 15 | tr -d '\n' | head -c 20)
        FATESAIKOU_TMP_PASS=$(openssl rand -base64 15 | tr -d '\n' | head -c 20)
        SSHPROXY_TMP_PASS=$(openssl rand -base64 15 | tr -d '\n' | head -c 20)

        # Mask TMP_PASS
        echo "::add-mask::$ROOT_PASS"
        echo "::add-mask::$FATESAIKOU_TMP_PASS"
        echo "::add-mask::$SSHPROXY_TMP_PASS"

        # Export to github env
        echo "ROOT_PASS=$ROOT_PASS" >> $GITHUB_ENV
        echo "FATESAIKOU_TMP_PASS=$FATESAIKOU_TMP_PASS" >> $GITHUB_ENV
        echo "SSHPROXY_TMP_PASS=$SSHPROXY_TMP_PASS" >> $GITHUB_ENV

    - name: Create a Linode instance
      env:
        FATESAIKOU_KEYS: ${{ secrets.FATESAIKOU_KEYS }}
        SSHPROXY_KEYS: ${{ secrets.SSHPROXY_KEYS }}
        ROOT_PASS: ${{ env.ROOT_PASS }}
        FATESAIKOU_TMP_PASS: ${{ env.FATESAIKOU_TMP_PASS }}
        SSHPROXY_TMP_PASS: ${{ env.SSHPROXY_TMP_PASS }}
      run: |
        # Create the Linode instance
        linode_cli_ret=$(
            linode-cli linodes create \
                --no-defaults \
                --label ${{ github.event.inputs.label }} \
                --region ${{ github.event.inputs.region }} \
                --type ${{ github.event.inputs.type }} \
                --image ${{ github.event.inputs.image }} \
                --root_pass $ROOT_PASS \
                --json \
                --metadata.user_data "$(cat ./cloud_config.yaml | envsubst | base64 | tr -d '\n')"
        )

        # echo the output to the console
        echo "<<<<<Linode instance created>>>>>"
        echo $linode_cli_ret | jq

        # Export Linode IP to github env
        LINODE_IP=$(echo $linode_cli_ret | jq -r '.[0] | .ipv4 | .[0]')
        echo "LINODE_IP=$LINODE_IP" >> $GITHUB_ENV

        # Wait ssh port(22) open
        while ! nc -w 1 -z $LINODE_IP 22; do
          echo "[$(date)] Waiting for the Linode to be ready..."
          sleep 1
        done

        # Wait ssh service is up
        EXEC_CMD="sshpass -p $ROOT_PASS ssh -o StrictHostKeyChecking=no root@$LINODE_IP"
        while [ "$($EXEC_CMD "echo 'success'" 2>/dev/null)" != "success" ]; do
          echo "[$(date)]SSH is up, but the system is not ready for command execution. Waiting..."
          sleep 1
        done

    - name: Copy files to the Linode instance
      env:
        ROOT_PASS: ${{ env.ROOT_PASS }}
        LINODE_IP: ${{ env.LINODE_IP }}
      run: |
        EXEC_CMD="sshpass -p $ROOT_PASS ssh -o StrictHostKeyChecking=no root@$LINODE_IP"
        SCP_CMD="sshpass -p $ROOT_PASS scp -o StrictHostKeyChecking=no"

        (
          cd static_normal_files
          $SCP_CMD -r * root@$LINODE_IP:/
        )

        # Chown for fatesaikou and sshproxy
        $EXEC_CMD "chown -R fatesaikou:fatesaikou /home/fatesaikou"
        $EXEC_CMD "chown -R sshproxy:sshproxy /home/sshproxy"

    - name: Initialize softwares for fatesaikou
      env:
        FATESAIKOU_TMP_PASS: ${{ env.FATESAIKOU_TMP_PASS }}
        LINODE_IP: ${{ env.LINODE_IP }}
      run: |
        EXEC_CMD="sshpass -p $FATESAIKOU_TMP_PASS ssh -t -o StrictHostKeyChecking=no fatesaikou@$LINODE_IP"

        # Initialize vim
        echo "Hello world!"
        $EXEC_CMD "git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim"
        echo "Hello world!!"
        $EXEC_CMD "vim -E +PluginInstall +qall 1>/dev/null 2>&1 || exit 0" # allow all errors

        # Initialize tmux
        echo "Hello world!!!"
        $EXEC_CMD "git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm"
        echo "Hello world!!!!"
        $EXEC_CMD "~/.tmux/plugins/tpm/bin/install_plugins"
        echo "Hello world!!!!!"

    - name: Lock password for fatesaikou and sshproxy and disable remote login of root
      env:
        ROOT_PASS: ${{ env.ROOT_PASS }}
        LINODE_IP: ${{ env.LINODE_IP }}
      run: |
        EXEC_CMD="sshpass -p $ROOT_PASS ssh -o StrictHostKeyChecking=no root@$LINODE_IP"

        $EXEC_CMD "passwd -l fatesaikou"
        $EXEC_CMD "passwd -l sshproxy"
        $EXEC_CMD "sed -i '/PermitRootLogin/d' /etc/ssh/sshd_config"
        $EXEC_CMD "echo \"PermitRootLogin no\" >> /etc/ssh/sshd_config"
        $EXEC_CMD "systemctl restart sshd"
