name: Create linode

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        description: instance label
        required: true
        default: fws
      region:
        type: string
        description: instance region
        required: true
        default: ap-northeast
      type:
        type: string
        description: instance type
        required: true
        default: g6-nanode-1
      image:
        type: string
        description: instance image
        required: true
        default: linode/ubuntu24.04
  workflow_call:
    inputs:
      label:
        type: string
        description: instance label
        required: true
        default: fws
      region:
        type: string
        description: instance region
        required: true
        default: ap-northeast
      type:
        type: string
        description: instance type
        required: true
        default: g6-nanode-1
      image:
        type: string
        description: instance image
        required: true
        default: linode/ubuntu24.04
      
jobs:
  create_linode:
    name: create linode
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Install the Linode CLI
      uses: linode/action-linode-cli@v1
      with:
        token: ${{ secrets.LINODE_TOKEN }}

    - name: Install nessary tools
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Build file bundle for Linode
      env:
        FILE_CRYPTO_KEY: ${{ secrets.FILE_CRYPTO_KEY }}
      run: |
        # create file base dir
        mkdir to_sync_files

        # copy normal files to to_sync_files
        cp -r static_normal_files/* to_sync_files/

        # decrypt secret files and copy to to_sync_files
        cfs=($(find static_secret_files -type f -name '*.crypted'))
        for cf in "${cfs[@]}"; do
          dst_file=${cf/static_secret_files/to_sync_files}
          dst_file=${dst_file%.crypted}

          mkdir -p $(dirname $dst_file)

          echo "Decrypting $cf..."
          cat $cf | ./scripts/decryptStdin.sh $FILE_CRYPTO_KEY > $dst_file
        done

    - name: Generate tmp password
      run: |
        ROOT_PASS=$(openssl rand -base64 15 | tr -d '\n' | head -c 20)
        FATESAIKOU_TMP_PASS=$(openssl rand -base64 15 | tr -d '\n' | head -c 20)
        SSHPROXY_TMP_PASS=$(openssl rand -base64 15 | tr -d '\n' | head -c 20)

        # Mask TMP_PASS
        # echo "::add-mask::$ROOT_PASS"
        # echo "::add-mask::$FATESAIKOU_TMP_PASS"
        # echo "::add-mask::$SSHPROXY_TMP_PASS"

        # Export to github env
        echo "ROOT_PASS=$ROOT_PASS" >> $GITHUB_ENV
        echo "FATESAIKOU_TMP_PASS=$FATESAIKOU_TMP_PASS" >> $GITHUB_ENV
        echo "SSHPROXY_TMP_PASS=$SSHPROXY_TMP_PASS" >> $GITHUB_ENV

    - name: Create a Linode instance
      env:
        ROOT_PASS: ${{ env.ROOT_PASS }}
        FATESAIKOU_TMP_PASS: ${{ env.FATESAIKOU_TMP_PASS }}
        SSHPROXY_TMP_PASS: ${{ env.SSHPROXY_TMP_PASS }}
      run: |
        # Create the Linode instance
        linode_cli_ret=$(
            linode-cli linodes create \
                --no-defaults \
                --label ${{ github.event.inputs.label }} \
                --region ${{ github.event.inputs.region }} \
                --type ${{ github.event.inputs.type }} \
                --image ${{ github.event.inputs.image }} \
                --root_pass $ROOT_PASS \
                --json \
                --metadata.user_data "$(cat ./cloud_config.yaml | envsubst | base64 | tr -d '\n')"
        )

        # echo the output to the console
        echo "<<<<<Linode instance created>>>>>"
        echo $linode_cli_ret | jq

        # Export Linode IP to github env
        LINODE_IP=$(echo $linode_cli_ret | jq -r '.[0] | .ipv4 | .[0]')
        echo "LINODE_IP=$LINODE_IP" >> $GITHUB_ENV

        # Wait ssh service is up
        EXEC_CMD="sshpass -p $ROOT_PASS ssh -o ConnectTimeout=1 -o StrictHostKeyChecking=no root@$LINODE_IP"
        while [ "$($EXEC_CMD "echo 'success'" 2>/dev/null)" != "success" ]; do
          echo "[$(date)] Waiting SSH..."
          sleep 1
        done

    - name: Copy files to the Linode instance
      env:
        ROOT_PASS: ${{ env.ROOT_PASS }}
        LINODE_IP: ${{ env.LINODE_IP }}
      run: |
        EXEC_CMD="sshpass -p $ROOT_PASS ssh -o StrictHostKeyChecking=no root@$LINODE_IP"
        SCP_CMD="sshpass -p $ROOT_PASS scp -o StrictHostKeyChecking=no"

        $SCP_CMD -r to_sync_files/* root@$LINODE_IP:/
        rm -rf to_sync_files

        # Chown for fatesaikou and sshproxy
        $EXEC_CMD "chown -R fatesaikou:fatesaikou /home/fatesaikou"
        $EXEC_CMD "chown -R sshproxy:sshproxy /home/sshproxy"

    - name: Initialize softwares for fatesaikou
      env:
        FATESAIKOU_TMP_PASS: ${{ env.FATESAIKOU_TMP_PASS }}
        LINODE_IP: ${{ env.LINODE_IP }}
      run: |
        EXEC_CMD="sshpass -p $FATESAIKOU_TMP_PASS ssh -o StrictHostKeyChecking=no fatesaikou@$LINODE_IP"

        while [ "$($EXEC_CMD "echo 'success'" 2>/dev/null)" != "success" ]; do
          echo "[$(date)] Waiting SSH..."
          sleep 1
        done

        $EXEC_CMD "
          # Initialize vim
          git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim;
          vim -E -s -u ~/.vimrc +PluginInstall +qall || exit 0;

          # Initialize tmux
          git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm;
          ~/.tmux/plugins/tpm/bin/install_plugins;
        "

    - name: Lock password for fatesaikou and sshproxy and disable remote login of root
      env:
        ROOT_PASS: ${{ env.ROOT_PASS }}
        LINODE_IP: ${{ env.LINODE_IP }}
      run: |
        EXEC_CMD="sshpass -p $ROOT_PASS ssh -o StrictHostKeyChecking=no root@$LINODE_IP"

        while [ "$($EXEC_CMD "echo 'success'" 2>/dev/null)" != "success" ]; do
          echo "[$(date)] Waiting SSH..."
          sleep 1
        done

        $EXEC_CMD "
          # passwd -l fatesaikou
          # passwd -l sshproxy
          # sed -i '/PermitRootLogin/d' /etc/ssh/sshd_config
          # echo \"PermitRootLogin no\" >> /etc/ssh/sshd_config
          # systemctl reload ssh.service
        "

