name: Create linode

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        description: instance label
        required: true
        default: fws
      region:
        type: string
        description: instance region
        required: true
        default: ap-northeast
      type:
        type: string
        description: instance type
        required: true
        default: g6-nanode-1
      image:
        type: string
        description: instance image
        required: true
        default: linode/ubuntu24.04
  workflow_call:
    inputs:
      label:
        type: string
        description: instance label
        required: true
        default: fws
      region:
        type: string
        description: instance region
        required: true
        default: ap-northeast
      type:
        type: string
        description: instance type
        required: true
        default: g6-nanode-1
      image:
        type: string
        description: instance image
        required: true
        default: linode/ubuntu24.04
      
jobs:
  create_linode:
    name: create linode
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Install the Linode CLI
      uses: linode/action-linode-cli@v1
      with:
        token: ${{ secrets.LINODE_TOKEN }}

    - name: Install nessary tools
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Create a Linode instance
      run: |
        ROOT_PASS=$(openssl rand -base64 15 | tr -d '\n' | head -c 20)

        # Create the Linode instance
        linode_cli_ret=$(
            linode-cli linodes create \
                --no-defaults \
                --label ${{ github.event.inputs.label }} \
                --region ${{ github.event.inputs.region }} \
                --type ${{ github.event.inputs.type }} \
                --image ${{ github.event.inputs.image }} \
                --root_pass $ROOT_PASS \
                --json \
                --metadata.user_data "$(cat ./cloud_config.yaml | envsubst | base64 | tr -d '\n')"
        )

        # echo the output to the console
        echo "<<<<<Linode instance created>>>>>"
        echo $linode_cli_ret | jq
        
        echo "ROOT_PASS=$ROOT_PASS" >> $GITHUB_ENV
        echo "LINODE_IP=$(echo $linode_cli_ret | jq -r '.[0] | .ipv4 | .[0]')" >> $GITHUB_ENV

        # Wait until the Linode is ready(port 22 is open)
        linode_ip=$(echo $linode_cli_ret | jq -r '.[0] | .ipv4 | .[0]')
        while ! nc -w 1 -z $linode_ip 22; do
            echo "Waiting for the Linode to be ready..."
            sleep 5
        done
      env:
        FATESAIKOU_KEYS: ${{ secrets.FATESAIKOU_KEYS }}
        SSHPROXY_KEYS: ${{ secrets.SSHPROXY_KEYS }}

    - name: Copy files to the Linode instance
      run: |
        SCP_CMD="sshpass -p $ROOT_PASS scp -o StrictHostKeyChecking=no"
    
        $SCP_CMD -r ./static_normal_files root@${{ env.LINODE_IP }}:/

    - name: Initialize vim, tmux
      run: |
        EXEC_CMD="sshpass -p $ROOT_PASS ssh -o StrictHostKeyChecking=no root@$LINODE_IP"

        # Initialize vim
        $EXEC_CMD "git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim"
        $EXEC_CMD "vim +PluginInstall +qall"

        # Initialize tmux
        $EXEC_CMD "git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm"
        $EXEC_CMD "~/.tmu x/plugins/tpm/bin/install_plugins"

    - name: Chown for fatesaikou
      run: |
        EXEC_CMD="sshpass -p $ROOT_PASS ssh -o StrictHostKeyChecking=no root@$LINODE_IP"

        $EXEC_CMD "chown -R fatesaikou:fatesaikou /home/fatesaikou"

    - name: Disable remote login of root
      run: |
        EXEC_CMD="sshpass -p $ROOT_PASS ssh -o StrictHostKeyChecking=no root@$LINODE_IP"

        $EXEC_CMD "sed -i '/PermitRootLogin/d' /etc/ssh/sshd_config"
        $EXEC_CMD "echo \"PermitRootLogin no\" >> /etc/ssh/sshd_config"
        $EXEC_CMD "systemctl restart sshd"
