name: Delete linode

on:
  workflow_call:
    inputs:
      label:
        type: string
        description: instance label
        required: true
        default: fws
      
jobs:
  delete_linode:
    name: delete linode
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Install the Linode CLI
      uses: linode/action-linode-cli@v1
      with:
        token: ${{ secrets.LINODE_TOKEN }}

    - name: Delete a Linode instance
      run: |
        LABEL="${{ inputs.label }}"

        linode_id=$(linode-cli linodes list --json | jq -r ".[] | select(.label == \"$LABEL\") | .id")
        linode-cli linodes rm "$linode_id"
