name: Restart linode

on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        description: instance label
        required: true
        default: fws
      region:
        type: string
        description: instance region
        required: true
        default: ap-northeast
      type:
        type: string
        description: instance type
        required: true
        default: g6-nanode-1
      image:
        type: string
        description: instance image
        required: true
        default: linode/ubuntu24.04

jobs:
  create_linode:
    uses: ./.github/workflows/create_linode.yaml
    permissions:
      contents: read
      id-token: write
    with:
      label: ${{ github.event.inputs.label }}-preview
      region: ${{ github.event.inputs.region }}
      type: ${{ github.event.inputs.type }}
      image: ${{ github.event.inputs.image }}
    secrets: inherit

  delete_linode:
    needs: [create_linode]
    uses: ./.github/workflows/delete_linode.yaml
    with:
      label: ${{ github.event.inputs.label }}
      region: ${{ github.event.inputs.region }}
    secrets: inherit

  promote_preview_linode:
    needs: [delete_linode]
    uses: ./.github/workflows/promote_preview_linode.yaml
    with:
      label: ${{ github.event.inputs.label }}
      preview_label: ${{ github.event.inputs.label }}-preview
      region: ${{ github.event.inputs.region }}
    secrets: inherit
